spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security_demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 111111
  # 暂时关闭session存储
  session:
    store-type: none
server:
  port: 9091
# 暂时关闭security http basic验证
#security:
#  basic:
#    enabled: false